default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: second_to_none_pass
  pool: 5

development:
  <<: *default
  database: second_to_none_development

test:
  <<: *default
  database: second_to_none_test

production:
  <<: *default
  database: second_to_none_production
  username: <%= ENV["SECOND_TO_NONE_DATABASE_USER"] %>
  host: <%= ENV["SECOND_TO_NONE_DATABASE_HOST"] %>
  password: <%= ENV["SECOND_TO_NONE_DATABASE_PASSWORD"] %>
